# Generated by Django 2.2.7 on 2019-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatefield',
            name='field',
            field=models.CharField(max_length=36, verbose_name='field'),
        ),
    ]
